### ISSUE TITLE
Could you make it so that the app closes during the night when we are not walking and save battery

### ISSUE THREAD

**Issue by 1LightningBoy1** [bk20dev/forest#9]
Maybe just add an option for that.(just installed the app and it's amazing)

**Comment by Lostking24** [comment]
Use an app called macro driod set up a rule that at certain days or times to close the app 😁

**Comment by bk20dev** [comment]
Hi! I am glad to hear you liked the app! Forest currently uses a very lightweight service to track user steps. For me it ends up using about 0.29% of battery - and it's not that much. The feature you suggested would introduce some new challenges and make the app less stable due to how different Android manufacturers implemented their 'battery optimisations'. It often causes undesired behaviours, like removing scheduled tasks. In other words, the app might not be able to start at a specified time. Speaking of time, some people, including me, sometimes happen to walk during the night, so closing the app during nighttime will cause the steps not to be counted. So if you want the app to be stopped during night, I would suggest following the Lostking's suggestion (I have never used macro droid or any app like this, so you do it on your own risk). Just don't forget to open Forest in the morning 🌲

**Comment by bk20dev** [comment]
Hi! I am glad to hear you liked the app! Forest currently uses a very lightweight service to track user steps. For me it ends up using about 0.29% of battery - and it's not that much. The feature you suggested would introduce some new challenges and make the app less stable due to how different Android manufacturers implemented their 'battery optimisations'. It often causes undesired behaviours, like removing scheduled tasks. In other words, the app might not be able to start at a specified time. Speaking of time, some people, including me, sometimes happen to walk during the night, so closing the app during nighttime will cause the steps not to be counted. So if you want the app to be stopped during night, I would suggest following the Lostking's suggestion (I have never used macro droid or any app like this, so you do it on your own risk). Just don't forget to open Forest in the morning 🌲
